# Generated by Django 5.2.1 on 2025-06-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sucursales/'),
        ),
    ]
